### ISSUE TITLE
voigt_profile

### ISSUE THREAD

**Issue by yevgenyr** [DanPorter/Dans_Diffraction#7]
Hi Dan,
Great code - thanks! 

I was wondering if you have plans to add a voigt peak shape (see [here](https://linuxtut.com/en/def7848f9194151e540c/)). 

I remember that realistically, line profiles usually have this lineshape. Gaussians are usually rare.

it can be something like:
```
t = np.arange(-1000, 1000, 0.1) 
fwhmg = 2  
fwhml = 2 
v = sps.voigt_profile(t, fwhmg, fwhml) 
I = np.convolve(I, v, 'same') 
```
inside `Scatter.generate_powder`.  (`I` is the pxrd profile with delta functions)

**Comment by DanPorter** [comment]
Hi yevgenyr,

Thanks for your message and glad to hear you like the code!

That's a great idea and something I had planned on adding at some point (when someone asked for it). Now you have asked, I'll find a way to add this feature :)

Best wishes,

Dan

**Comment by yevgenyr** [comment]
Thanks Dan,
If you'de like I can also contribute in a way of Pull Requests as I go. 
I am working on integrating a different CIF reader (from diffpy - it is a bit more comprehansive) and map it over to your cif reader.  (of course feel free to reject/modify my PRs :))

**Comment by DanPorter** [comment]
Hi yevgenyr,
I've just committed a new version (V2.2.0) with some new features on the calculation of powder patterns:
```python
twotheta, intensity, reflections = xtl.Scatter.powder('xray', units='twotheta', energy_kev=8, lorentz_fraction=0.5, custom_peak=None)
```
The are new inputs (all can also be set using xtl.Scatter.setup_scatter):
 - units: something like 'Q', 'dspacing' or 'twotheta'
 - lorentz_fraction: the ratio of Gaussian/Lorentzian widths in pseudo-Voight
 - custom_peak: if an array is given, this is convolved with the intensity delta-functions, rather than the pseudo-Voight. 

And there are new outputs:
 - twotheta: array of spectrum angles
 - intensity: array of spectrum intensity
 - reflections: array of grouped reflections (h,k,l,twotheta,intensity)

I've added an example showing this functionality in the [examples folder.](https://github.com/DanPorter/Dans_Diffraction/blob/master/Examples/example_generate_powder_custom_profile.py)

Please do have a go and see what you think! If you spot any problems let me know.

Out of interest - what features does the diffpy CIF reader have that aren't in my (admittedly pretty simple) one?
